In [1]:
import datetime
d = datetime.datetime.now()

In [2]:
datetime.datetime.now()

datetime.datetime(2019, 11, 21, 15, 31, 11, 662640)

In [3]:
d.year

2019

In [4]:
d.month

11

In [5]:
d.day

21

In [6]:
d.hour

15

In [7]:
d.minute

31

In [8]:
d.second

11

In [9]:
d.microsecond

495081

In [10]:
import calendar

In [11]:
cal = calendar.month(2019, 11)
print(cal)

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [12]:
cal

'   November 2019\nMo Tu We Th Fr Sa Su\n             1  2  3\n 4  5  6  7  8  9 10\n11 12 13 14 15 16 17\n18 19 20 21 22 23 24\n25 26 27 28 29 30\n'

In [13]:
cal = calendar.monthrange(2019, 11)
print(cal)

(4, 30)


In [14]:
cal = calendar.weekday(2019, 11, 5)
print(cal)

1


In [15]:
calendar.leapdays(2000, 2020)

5

In [ ]:
calendar.isleap(2019)

False

In [ ]:
calendar.prcal(2019)

                                  2019

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6                   1  2  3                   1  2  3
 7  8  9 10 11 12 13       4  5  6  7  8  9 10       4  5  6  7  8  9 10
14 15 16 17 18 19 20      11 12 13 14 15 16 17      11 12 13 14 15 16 17
21 22 23 24 25 26 27      18 19 20 21 22 23 24      18 19 20 21 22 23 24
28 29 30 31               25 26 27 28               25 26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7             1  2  3  4  5                      1  2
 8  9 10 11 12 13 14       6  7  8  9 10 11 12       3  4  5  6  7  8  9
15 16 17 18 19 20 21      13 14 15 16 17 18 19      10 11 12 13 14 15 16
22 23 24 25 26 27 28      20 21 22 23 24 25 26      17 18 19 20 21 22 23
29 30                     

In [ ]:
import time

In [ ]:
localtime = time.localtime(time.time())
localtime

time.struct_time(tm_year=2019, tm_mon=11, tm_mday=21, tm_hour=15, tm_min=31, tm_sec=13, tm_wday=3, tm_yday=325, tm_isdst=0)

In [ ]:
from datetime import date
today = date.today()
today

datetime.date(2019, 11, 21)

In [ ]:
d1 = today.strftime("%d %B %y")
d1

'21 November 19'

In [ ]:
d1 = today.strftime("%d %b %y")
d1

'21 Nov 19'

In [ ]:
d1 = today.strftime("%d %m %y")
d1

'21 11 19'

In [ ]:
a = 9
print(type(a))

<class 'int'>


In [ ]:
from tkinter import *
tk = Tk()
canvas = Canvas(tk, width=400, height=400)
canvas.pack()
canvas.create_arc(10, 10, 200, 100, extent=180, style=ARC)
tk.mainloop()

In [ ]:
import turtle
t = turtle.Pen()
t.color(1, 0, 0)
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(20)
t.left(90)
t.forward(20)
t.right(90)
t.forward(20)

In [ ]:
from tkinter import *
tk = Tk()
btn = Button(tk, text="Click me")
btn.pack()
tk.mainloop()

## Numpy

In [2]:
# Generate some random data

import numpy as np
data = np.random.randn(2,3)
print(data)

[[-0.73790376  0.97433937  0.39553607]
 [ 1.26990394  2.27039667 -0.79150308]]


In [3]:
data = np.array([[12,23,34],[67,54,32],[89,76,54]])
print(data)

[[12 23 34]
 [67 54 32]
 [89 76 54]]


In [4]:
data *10

array([[120, 230, 340],
       [670, 540, 320],
       [890, 760, 540]])

In [5]:
data + data

array([[ 24,  46,  68],
       [134, 108,  64],
       [178, 152, 108]])

In [6]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [8]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [9]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [11]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [12]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [13]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [14]:
arr = np.arange(10.0)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5:8]

array([5, 6, 7])

In [18]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [19]:
range(10)

range(0, 10)

In [20]:
range(10.0)

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [22]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [23]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [24]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr2_slice = arr2[6:9]
arr2_slice

array([6, 7, 8])

In [28]:
arr2[6:9] = 20
arr2

array([ 0,  1,  2,  3,  4,  5, 20, 20, 20,  9])

In [29]:
arr2_slice[2] = 32
arr2_slice

array([20, 20, 32])

In [30]:
arr2

array([ 0,  1,  2,  3,  4,  5, 20, 20, 32,  9])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2-Dimensional Array

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

In [ ]:
arr2d[:2,1:]

In [ ]:
arr2d[1,:2]

In [ ]:
arr2d[:2,2]

In [ ]:
arr2d[:,:1]

In [ ]:
arr2d[:2,1:]

In [ ]:
arr2d[:1,1:] = 0
arr2d

In [ ]:
arr2d[2:2,1:2]=0
arr2d

In [ ]:
arr2d[2][1]=10
arr2d

## Examples for Boolean Indexing

In [ ]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

In [ ]:
data = np.random.randn(7,4)
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]

In [ ]:
data[names == 'Bob',3:]

In [ ]:
data[names != 'Bob']

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask

In [ ]:
data[mask]

In [ ]:
data[data<0]=0
data

In [ ]:
data[names !='Joe']=7
data

## Fancy Indexing

In [32]:
arr = np.empty((8,4))
arr

array([[2.78149851e-307, 8.06624924e-308, 1.20161933e-306,
        2.78149001e-307],
       [4.00538080e-307, 6.23040373e-307, 2.22520627e-307,
        1.76128468e-312],
       [2.22520627e-307, 4.00540457e-307, 5.34042511e-307,
        6.23040373e-307],
       [1.60219035e-306, 2.78146625e-307, 1.60211429e-306,
        1.78020440e-306],
       [7.56599807e-307, 8.90104239e-307, 6.89772896e-307,
        3.56039998e-307],
       [6.23040373e-307, 1.60219035e-306, 2.78146625e-307,
        1.60211429e-306],
       [1.78020440e-306, 7.56599807e-307, 8.90104239e-307,
        8.45590538e-307],
       [7.56593017e-307, 6.23058028e-307, 1.95225102e-312,
        6.89803114e-307]])

In [33]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [34]:
# Subset of the rows

arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [36]:
# using negative indices
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [37]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [38]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [39]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [40]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [42]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [44]:
arr = np.arange(16).reshape((2,2,4))  # Here 2--> no.of matrices, 2-->no.of rows and 4--> no.of columns
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

-        2  2  4
- index  0  1  2

In [48]:
arr.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

In [45]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [46]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [47]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Pandas

In [49]:
import pandas as pd

In [50]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [51]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [52]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
obj.dtype

dtype('int64')

In [54]:
obj2 = pd.Series([4,7,-5,3],index = ['a','b','c','d'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [55]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [56]:
obj2['a']

4

In [57]:
obj2['d'] = 10

In [58]:
obj2

a     4
b     7
c    -5
d    10
dtype: int64

In [59]:
obj2[obj2>0]

a     4
b     7
d    10
dtype: int64

In [60]:
obj2*2

a     8
b    14
c   -10
d    20
dtype: int64

In [61]:
np.exp(obj2)

a       54.598150
b     1096.633158
c        0.006738
d    22026.465795
dtype: float64

In [62]:
'b' in obj2

True

In [63]:
'e' in obj2

False

In [66]:
sdata = {'Ohio':35000, 'Texas':71000,'Oregon':16000,'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [67]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [68]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [69]:
pd.notnull(obj4
          )

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [70]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [71]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [72]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [73]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [74]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64